import stylistic from "@stylistic/eslint-plugin";
import antfu from "eslint-plugin-antfu";
import imports from "eslint-plugin-import-x";
import perfectionist from "eslint-plugin-perfectionist";
import unicorn from "eslint-plugin-unicorn";
import { defineConfig } from "eslint/config";

export default defineConfig([
  {
    name: "stylistic",
    plugins: {
      antfu,
      stylistic,
      perfectionist,
      imports,
      unicorn,
    },
    rules: {
      ...unicorn.configs.recommended.rules,
      "unicorn/no-nested-ternary": "off",
      "unicorn/consistent-function-scoping": "off",
      "unicorn/prevent-abbreviations": ["error", {
        replacements: {
          props: false,
          args: false,
          params: false,
          fn: false,
          db: false,
          env: false,
          req: false,
          utils: false,
        },
      }],
      "unicorn/prefer-ternary": "off",
      "unicorn/no-null": "off",
      "unicorn/filename-case": ["error", {
        cases: {
          camelCase: true,
          pascalCase: true,
          kebabCase: true,
        },
      }],
      "perfectionist/sort-exports": ["error", { order: "asc", type: "natural" }],
      "perfectionist/sort-imports": ["error", {
        groups: [
          "type",
          ["parent-type", "sibling-type", "index-type", "internal-type"],
          "builtin",
          "external",
          { newlinesBetween: 1 },
          "server",
          { newlinesBetween: 1 },
          "components",
          { newlinesBetween: 1 },
          "modules",
          "internal",
          { newlinesBetween: 1 },
          ["parent", "sibling", "index"],
          "side-effect",
          "object",
          "unknown",
        ],
        customGroups: [
          {
            groupName: "components",
            elementNamePattern: ["^@/components/.*$"],
          },
          {
            groupName: "modules",
            elementNamePattern: ["^@/modules/.*$"],
          },
          {
            groupName: "server",
            elementNamePattern: ["^@server/.*$"],
          },
        ],
        newlinesBetween: 0,
        order: "asc",
        type: "natural",
      }],
      "perfectionist/sort-named-exports": ["error", { order: "asc", type: "natural" }],
      "perfectionist/sort-named-imports": ["error", { order: "asc", type: "natural" }],
      "stylistic/array-bracket-spacing": ["error", "never"],
      "stylistic/array-element-newline": ["error", "consistent"],
      "stylistic/arrow-parens": ["error", "always"],
      "stylistic/arrow-spacing": ["error", { before: true, after: true }],
      "stylistic/block-spacing": ["error", "always"],
      "stylistic/brace-style": ["error", "1tbs", { allowSingleLine: false }],
      "stylistic/comma-dangle": ["error", "always-multiline"],
      "stylistic/comma-spacing": ["error", { before: false, after: true }],
      "stylistic/comma-style": ["error", "last"],
      "stylistic/computed-property-spacing": ["error", "never"],
      "stylistic/curly-newline": ["error", "always"],
      "stylistic/dot-location": ["error", "property"],
      "stylistic/eol-last": ["error", "always"],
      "stylistic/function-call-argument-newline": ["error", "consistent"],
      "stylistic/function-paren-newline": ["error", "consistent"],
      "stylistic/function-call-spacing": ["error", "never"],
      "stylistic/generator-star-spacing": ["error", { before: true, after: false }],
      "stylistic/implicit-arrow-linebreak": ["error", "beside"],
      "stylistic/indent": ["error", 2],
      "stylistic/indent-binary-ops": ["error", 2],
      "stylistic/jsx-child-element-spacing": "error",
      "stylistic/jsx-curly-brace-presence": ["error", {
        props: "never",
        children: "never",
        propElementValues: "always",
      }],
      "stylistic/jsx-curly-newline": ["error", "consistent"],
      "stylistic/jsx-curly-spacing": ["error", { when: "never" }],
      "stylistic/jsx-equals-spacing": ["error", "never"],
      "stylistic/jsx-first-prop-new-line": ["error", "multiline"],
      "stylistic/jsx-function-call-newline": ["error", "always"],
      "stylistic/jsx-max-props-per-line": ["error", { maximum: 1 }],
      "stylistic/jsx-pascal-case": "error",
      "stylistic/jsx-quotes": ["error", "prefer-double"],
      "stylistic/jsx-self-closing-comp": "error",
      "stylistic/jsx-sort-props": ["error", {
        noSortAlphabetically: true,
        shorthandFirst: true,
        callbacksLast: true,
      }],
      "stylistic/jsx-tag-spacing": ["error", {
        closingSlash: "never",
        beforeSelfClosing: "always",
        afterOpening: "never",
        beforeClosing: "allow",
      }],
      "stylistic/key-spacing": ["error", { beforeColon: false }],
      "stylistic/keyword-spacing": ["error", { before: true }],
      "stylistic/line-comment-position": ["error", { position: "above" }],
      "stylistic/linebreak-style": ["error", "unix"],
      "stylistic/lines-between-class-members": ["error", "always"],
      "stylistic/max-statements-per-line": ["error", { max: 1 }],
      "stylistic/member-delimiter-style": ["error", {
        multiline: {
          delimiter: "semi",
          requireLast: true,
        },
        singleline: {
          delimiter: "semi",
          requireLast: false,
        },
        multilineDetection: "brackets",
      }],
      "stylistic/multiline-comment-style": ["error", "starred-block"],
      "stylistic/new-parens": "error",
      "stylistic/no-extra-parens": ["error", "all", { ignoreJSX: "all" }],
      "stylistic/no-extra-semi": "error",
      "stylistic/no-floating-decimal": "error",
      "stylistic/no-mixed-spaces-and-tabs": "error",
      "stylistic/no-multiple-empty-lines": ["error", {
        max: 1,
        maxEOF: 0,
      }],
      "stylistic/no-tabs": "error",
      "stylistic/no-trailing-spaces": "error",
      "stylistic/no-whitespace-before-property": "error",
      "stylistic/object-curly-spacing": ["error", "always"],
      "stylistic/one-var-declaration-per-line": ["error", "always"],
      "stylistic/operator-linebreak": ["error", "before"],
      "stylistic/padded-blocks": ["error", "never"],
      "stylistic/quote-props": ["error", "as-needed"],
      "stylistic/quotes": ["error", "double"],
      "stylistic/rest-spread-spacing": ["error", "never"],
      "stylistic/semi": ["error", "always"],
      "stylistic/semi-spacing": "error",
      "stylistic/semi-style": ["error", "last"],
      "stylistic/space-before-blocks": "error",
      "stylistic/space-before-function-paren": ["error", {
        anonymous: "always",
        named: "never",
        asyncArrow: "always",
        catch: "always",
      }],
      "stylistic/space-in-parens": ["error", "never"],
      "stylistic/space-infix-ops": "error",
      "stylistic/space-unary-ops": "error",
      "stylistic/spaced-comment": ["error", "always"],
      "stylistic/switch-colon-spacing": "error",
      "stylistic/template-curly-spacing": "error",
      "stylistic/template-tag-spacing": "error",
      "stylistic/type-annotation-spacing": "error",
      "stylistic/type-generic-spacing": "error",
      "stylistic/type-named-tuple-spacing": ["error"],
      "stylistic/wrap-iife": ["error", "outside"],
      "stylistic/wrap-regex": "error",
      "stylistic/yield-star-spacing": ["error", "before"],
      "stylistic/no-multi-spaces": "error",
      "antfu/consistent-chaining": "error",
      "antfu/consistent-list-newline": "error",
      "antfu/import-dedupe": "error",
      "antfu/top-level-function": "error",
      curly: ["error", "all"],
    },
  },
]);
