import { defineConfig } from "oxlint";

export default defineConfig({
  options: {
    denyWarnings: true,
    reportUnusedDisableDirectives: "error",
    typeAware: true,
    typeCheck: true,
  },
  plugins: ["typescript", "unicorn", "oxc", "import", "jsdoc", "promise", "vitest"],
  rules: {
    "eslint/accessor-pairs": "error",
    "eslint/array-callback-return": "error",
    "eslint/arrow-body-style": "off",
    "eslint/block-scoped-var": "error",
    "eslint/capitalized-comments": "error",
    "eslint/class-methods-use-this": "error",
    "eslint/complexity": ["error", 8],
    "eslint/constructor-super": "error",
    "eslint/curly": "error",
    "eslint/default-case": "error",
    "eslint/default-case-last": "error",
    "eslint/default-param-last": "error",
    "eslint/eqeqeq": "error",
    "eslint/for-direction": "error",
    "eslint/func-name-matching": "error",
    "eslint/func-names": "error",
    "eslint/func-style": ["error", "declaration"],
    "eslint/getter-return": "error",
    "eslint/grouped-accessor-pairs": "error",
    "eslint/guard-for-in": "error",
    "eslint/id-denylist": ["error", "foo", "bar", "baz", "thing", "stuff", "tmp", "doSomething"],
    "eslint/id-length": "off",
    "eslint/id-match": "error",
    "eslint/init-declarations": "error",
    "eslint/logical-assignment-operators": "error",
    "eslint/max-classes-per-file": "error",
    "eslint/max-depth": ["error", 3],
    "eslint/max-lines": [
      "error",
      {
        max: 500,
        skipBlankLines: true,
        skipComments: true,
      },
    ],
    "eslint/max-lines-per-function": [
      "error",
      {
        max: 40,
        skipBlankLines: true,
        skipComments: true,
      },
    ],
    "eslint/max-nested-callbacks": ["error", 3],
    "eslint/max-params": ["error", 3],
    "eslint/max-statements": ["error", 20],
    "eslint/new-cap": "error",
    "eslint/no-alert": "error",
    "eslint/no-array-constructor": "error",
    "eslint/no-async-promise-executor": "error",
    "eslint/no-await-in-loop": "error",
    "eslint/no-bitwise": "error",
    "eslint/no-caller": "error",
    "eslint/no-case-declarations": "error",
    "eslint/no-class-assign": "error",
    "eslint/no-compare-neg-zero": "error",
    "eslint/no-cond-assign": "error",
    "eslint/no-console": "error",
    "eslint/no-const-assign": "error",
    "eslint/no-constant-binary-expression": "error",
    "eslint/no-constant-condition": "error",
    "eslint/no-constructor-return": "error",
    "eslint/no-continue": "error",
    "eslint/no-control-regex": "error",
    "eslint/no-debugger": "error",
    "eslint/no-delete-var": "error",
    "eslint/no-div-regex": "error",
    "eslint/no-dupe-class-members": "error",
    "eslint/no-dupe-else-if": "error",
    "eslint/no-dupe-keys": "error",
    "eslint/no-duplicate-case": "error",
    "eslint/no-duplicate-imports": "off",
    "eslint/no-else-return": "error",
    "eslint/no-empty": "error",
    "eslint/no-empty-character-class": "error",
    "eslint/no-empty-function": "error",
    "eslint/no-empty-pattern": "error",
    "eslint/no-empty-static-block": "error",
    "eslint/no-eq-null": "error",
    "eslint/no-eval": "error",
    "eslint/no-ex-assign": "error",
    "eslint/no-extend-native": "error",
    "eslint/no-extra-bind": "error",
    "eslint/no-extra-boolean-cast": "error",
    "eslint/no-extra-label": "error",
    "eslint/no-fallthrough": "error",
    "eslint/no-func-assign": "error",
    "eslint/no-global-assign": "error",
    "eslint/no-implicit-coercion": "error",
    "eslint/no-implicit-globals": "error",
    "eslint/no-implied-eval": "error",
    "eslint/no-import-assign": "error",
    "eslint/no-inline-comments": "error",
    "eslint/no-inner-declarations": "error",
    "eslint/no-invalid-regexp": "error",
    "eslint/no-irregular-whitespace": "error",
    "eslint/no-iterator": "error",
    "eslint/no-label-var": "error",
    "eslint/no-labels": "error",
    "eslint/no-lone-blocks": "error",
    "eslint/no-lonely-if": "error",
    "eslint/no-loop-func": "error",
    "eslint/no-loss-of-precision": "error",
    "eslint/no-magic-numbers": "off",
    "eslint/no-misleading-character-class": "error",
    "eslint/no-multi-assign": "error",
    "eslint/no-multi-str": "error",
    "eslint/no-negated-condition": "error",
    "eslint/no-nested-ternary": "off",
    "eslint/no-new": "error",
    "eslint/no-new-func": "error",
    "eslint/no-new-native-nonconstructor": "error",
    "eslint/no-new-wrappers": "error",
    "eslint/no-nonoctal-decimal-escape": "error",
    "eslint/no-obj-calls": "error",
    "eslint/no-object-constructor": "error",
    "eslint/no-param-reassign": "error",
    "eslint/no-plusplus": "error",
    "eslint/no-promise-executor-return": "error",
    "eslint/no-proto": "error",
    "eslint/no-prototype-builtins": "error",
    "eslint/no-redeclare": "error",
    "eslint/no-regex-spaces": "error",
    "eslint/no-restricted-exports": [
      "error",
      {
        restrictedNamedExports: ["data", "result", "value", "helper", "manager"],
      },
    ],
    "eslint/no-restricted-globals": "error",
    "eslint/no-restricted-imports": "error",
    "eslint/no-restricted-properties": "error",
    "eslint/no-return-assign": "error",
    "eslint/no-script-url": "error",
    "eslint/no-self-assign": "error",
    "eslint/no-self-compare": "error",
    "eslint/no-sequences": "error",
    "eslint/no-setter-return": "error",
    "eslint/no-shadow": [
      "error",
      {
        hoist: "functions",
      },
    ],
    "eslint/no-shadow-restricted-names": "error",
    "eslint/no-sparse-arrays": "error",
    "eslint/no-template-curly-in-string": "error",
    "eslint/no-ternary": "off",
    "eslint/no-this-before-super": "error",
    "eslint/no-throw-literal": "error",
    "eslint/no-unassigned-vars": "error",
    "eslint/no-undef": "off",
    "eslint/no-undefined": "off",
    "eslint/no-underscore-dangle": "off",
    "eslint/no-unexpected-multiline": "error",
    "eslint/no-unmodified-loop-condition": "error",
    "eslint/no-unneeded-ternary": "error",
    "eslint/no-unreachable": "error",
    "eslint/no-unreachable-loop": "error",
    "eslint/no-unsafe-finally": "error",
    "eslint/no-unsafe-negation": "error",
    "eslint/no-unsafe-optional-chaining": "error",
    "eslint/no-unused-expressions": "error",
    "eslint/no-unused-labels": "error",
    "eslint/no-unused-private-class-members": "error",
    "eslint/no-unused-vars": "error",
    "eslint/no-use-before-define": "error",
    "eslint/no-useless-assignment": "error",
    "eslint/no-useless-backreference": "error",
    "eslint/no-useless-call": "error",
    "eslint/no-useless-catch": "error",
    "eslint/no-useless-computed-key": "error",
    "eslint/no-useless-concat": "error",
    "eslint/no-useless-constructor": "error",
    "eslint/no-useless-escape": "error",
    "eslint/no-useless-rename": "error",
    "eslint/no-useless-return": "error",
    "eslint/no-var": "error",
    "eslint/no-void": "error",
    "eslint/no-warning-comments": [
      "error",
      {
        decoration: [],
        location: "anywhere",
        terms: ["todo", "fixme", "xxx", "hack", "wip"],
      },
    ],
    "eslint/no-with": "error",
    "eslint/object-shorthand": "error",
    "eslint/one-var": "off",
    "eslint/operator-assignment": "error",
    "eslint/prefer-arrow-callback": "error",
    "eslint/prefer-const": "error",
    "eslint/prefer-destructuring": [
      "error",
      {
        AssignmentExpression: {
          array: false,
          object: true,
        },
        VariableDeclarator: {
          array: false,
          object: true,
        },
      },
    ],
    "eslint/prefer-exponentiation-operator": "error",
    "eslint/prefer-named-capture-group": "error",
    "eslint/prefer-numeric-literals": "error",
    "eslint/prefer-object-has-own": "error",
    "eslint/prefer-object-spread": "off",
    "eslint/prefer-promise-reject-errors": "error",
    "eslint/prefer-regex-literals": "error",
    "eslint/prefer-rest-params": "error",
    "eslint/prefer-spread": "error",
    "eslint/prefer-template": "error",
    "eslint/preserve-caught-error": "error",
    "eslint/radix": "error",
    "eslint/require-await": "error",
    "eslint/require-unicode-regexp": [
      "error",
      {
        requireFlag: "v",
      },
    ],
    "eslint/require-yield": "error",
    "eslint/sort-imports": "off",
    "eslint/sort-keys": "off",
    "eslint/sort-vars": "error",
    "eslint/symbol-description": "error",
    "eslint/unicode-bom": "error",
    "eslint/use-isnan": "error",
    "eslint/valid-typeof": "error",
    "eslint/vars-on-top": "off",
    "eslint/yoda": "error",
    "import/consistent-type-specifier-style": "error",
    "import/default": "error",
    "import/export": "error",
    "import/exports-last": "error",
    "import/extensions": "error",
    "import/first": "error",
    "import/group-exports": "error",
    "import/max-dependencies": [
      "error",
      {
        ignoreTypeImports: false,
        max: 8,
      },
    ],
    "import/named": "error",
    "import/namespace": "error",
    "import/newline-after-import": "error",
    "import/no-absolute-path": "error",
    "import/no-amd": "error",
    "import/no-anonymous-default-export": "error",
    "import/no-commonjs": [
      "error",
      {
        allowConditionalRequire: false,
      },
    ],
    "import/no-cycle": [
      "error",
      {
        ignoreTypes: false,
      },
    ],
    "import/no-default-export": "off",
    "import/no-duplicates": "error",
    "import/no-dynamic-require": "error",
    "import/no-empty-named-blocks": "error",
    "import/no-mutable-exports": "error",
    "import/no-named-as-default": "error",
    "import/no-named-as-default-member": "error",
    "import/no-named-default": "error",
    "import/no-named-export": "off",
    "import/no-namespace": [
      "error",
      {
        ignore: ["@stylexjs/stylex"],
      },
    ],
    "import/no-nodejs-modules": "error",
    "import/no-relative-parent-imports": "error",
    "import/no-self-import": "error",
    "import/no-unassigned-import": [
      "error",
      {
        allow: ["**/*.css"],
      },
    ],
    "import/no-webpack-loader-syntax": "error",
    "import/prefer-default-export": "off",
    "import/unambiguous": "error",
    "jsdoc/check-access": "error",
    "jsdoc/check-property-names": "error",
    "jsdoc/check-tag-names": "error",
    "jsdoc/empty-tags": "error",
    "jsdoc/implements-on-classes": "error",
    "jsdoc/no-blank-blocks": "error",
    "jsdoc/no-defaults": "error",
    "jsdoc/require-param": "error",
    "jsdoc/require-param-description": "error",
    "jsdoc/require-param-name": "error",
    "jsdoc/require-param-type": "off",
    "jsdoc/require-property": "error",
    "jsdoc/require-property-description": "error",
    "jsdoc/require-property-name": "error",
    "jsdoc/require-property-type": "error",
    "jsdoc/require-returns": "error",
    "jsdoc/require-returns-description": "error",
    "jsdoc/require-returns-type": "error",
    "jsdoc/require-throws-description": "error",
    "jsdoc/require-throws-type": "error",
    "jsdoc/require-yields": "error",
    "jsdoc/require-yields-description": "error",
    "jsdoc/require-yields-type": "error",
    "oxc/approx-constant": "error",
    "oxc/bad-array-method-on-arguments": "error",
    "oxc/bad-bitwise-operator": "error",
    "oxc/bad-char-at-comparison": "error",
    "oxc/bad-comparison-sequence": "error",
    "oxc/bad-match-all-arg": "error",
    "oxc/bad-min-max-func": "error",
    "oxc/bad-object-literal-comparison": "error",
    "oxc/bad-replace-all-arg": "error",
    "oxc/branches-sharing-code": "error",
    "oxc/const-comparisons": "error",
    "oxc/double-comparisons": "error",
    "oxc/erasing-op": "error",
    "oxc/misrefactored-assign-op": "error",
    "oxc/missing-throw": "error",
    "oxc/no-accumulating-spread": "error",
    "oxc/no-async-await": "off",
    "oxc/no-async-endpoint-handlers": "error",
    "oxc/no-barrel-file": [
      "error",
      {
        threshold: 0,
      },
    ],
    "oxc/no-const-enum": "error",
    "oxc/no-map-spread": [
      "error",
      {
        ignoreArgs: false,
        ignoreRereads: false,
      },
    ],
    "oxc/no-optional-chaining": "off",
    "oxc/no-rest-spread-properties": "off",
    "oxc/no-this-in-exported-function": "error",
    "oxc/number-arg-out-of-range": "error",
    "oxc/only-used-in-recursion": "error",
    "oxc/uninvoked-array-callback": "error",
    "promise/always-return": "error",
    "promise/avoid-new": "error",
    "promise/catch-or-return": "error",
    "promise/no-callback-in-promise": "error",
    "promise/no-multiple-resolved": "error",
    "promise/no-nesting": "error",
    "promise/no-new-statics": "error",
    "promise/no-promise-in-callback": "error",
    "promise/no-return-in-finally": "error",
    "promise/no-return-wrap": "error",
    "promise/param-names": "error",
    "promise/prefer-await-to-callbacks": "error",
    "promise/prefer-await-to-then": [
      "error",
      {
        strict: true,
      },
    ],
    "promise/prefer-catch": "error",
    "promise/spec-only": "error",
    "promise/valid-params": "error",
    "typescript/adjacent-overload-signatures": "error",
    "typescript/array-type": "error",
    "typescript/await-thenable": "error",
    "typescript/ban-ts-comment": [
      "error",
      {
        minimumDescriptionLength: 10,
        "ts-check": false,
        "ts-expect-error": "allow-with-description",
        "ts-ignore": true,
        "ts-nocheck": true,
      },
    ],
    "typescript/ban-tslint-comment": "error",
    "typescript/ban-types": "error",
    "typescript/class-literal-property-style": "error",
    "typescript/consistent-generic-constructors": "error",
    "typescript/consistent-indexed-object-style": "error",
    "typescript/consistent-return": "error",
    "typescript/consistent-type-assertions": [
      "error",
      {
        assertionStyle: "never",
      },
    ],
    "typescript/consistent-type-definitions": "error",
    "typescript/consistent-type-exports": "error",
    "typescript/consistent-type-imports": "error",
    "typescript/dot-notation": "error",
    "typescript/explicit-function-return-type": [
      "error",
      {
        allowConciseArrowFunctionExpressionsStartingWithVoid: false,
        allowDirectConstAssertionInArrowFunctions: false,
        allowExpressions: false,
        allowFunctionsWithoutTypeParameters: false,
        allowHigherOrderFunctions: false,
        allowIIFEs: false,
        allowTypedFunctionExpressions: false,
        allowedNames: [],
      },
    ],
    "typescript/explicit-member-accessibility": "error",
    "typescript/explicit-module-boundary-types": [
      "error",
      {
        allowArgumentsExplicitlyTypedAsAny: false,
        allowDirectConstAssertionInArrowFunctions: false,
        allowHigherOrderFunctions: false,
        allowOverloadFunctions: false,
        allowTypedFunctionExpressions: false,
        allowedNames: [],
      },
    ],
    "typescript/method-signature-style": "error",
    "typescript/no-array-delete": "error",
    "typescript/no-base-to-string": [
      "error",
      {
        checkUnknown: true,
        ignoredTypeNames: [],
      },
    ],
    "typescript/no-confusing-non-null-assertion": "error",
    "typescript/no-confusing-void-expression": "error",
    "typescript/no-deprecated": "error",
    "typescript/no-duplicate-enum-values": "error",
    "typescript/no-duplicate-type-constituents": "error",
    "typescript/no-dynamic-delete": "error",
    "typescript/no-empty-interface": "error",
    "typescript/no-empty-object-type": "error",
    "typescript/no-explicit-any": "error",
    "typescript/no-extra-non-null-assertion": "error",
    "typescript/no-extraneous-class": "error",
    "typescript/no-floating-promises": [
      "error",
      {
        allowForKnownSafeCalls: [],
        allowForKnownSafePromises: [],
        checkThenables: true,
        ignoreIIFE: false,
        ignoreVoid: false,
      },
    ],
    "typescript/no-for-in-array": "error",
    "typescript/no-implied-eval": "error",
    "typescript/no-import-type-side-effects": "error",
    "typescript/no-inferrable-types": "error",
    "typescript/no-invalid-void-type": "error",
    "typescript/no-meaningless-void-operator": "error",
    "typescript/no-misused-new": "error",
    "typescript/no-misused-promises": "error",
    "typescript/no-misused-spread": "error",
    "typescript/no-mixed-enums": "error",
    "typescript/no-namespace": "error",
    "typescript/no-non-null-asserted-nullish-coalescing": "error",
    "typescript/no-non-null-asserted-optional-chain": "error",
    "typescript/no-non-null-assertion": "error",
    "typescript/no-redundant-type-constituents": "error",
    "typescript/no-require-imports": "error",
    "typescript/no-restricted-types": "error",
    "typescript/no-this-alias": "error",
    "typescript/no-unnecessary-boolean-literal-compare": "error",
    "typescript/no-unnecessary-condition": "error",
    "typescript/no-unnecessary-parameter-property-assignment": "error",
    "typescript/no-unnecessary-qualifier": "error",
    "typescript/no-unnecessary-template-expression": "error",
    "typescript/no-unnecessary-type-arguments": "error",
    "typescript/no-unnecessary-type-assertion": "error",
    "typescript/no-unnecessary-type-constraint": "error",
    "typescript/no-unnecessary-type-conversion": "error",
    "typescript/no-unnecessary-type-parameters": "error",
    "typescript/no-unsafe-argument": "error",
    "typescript/no-unsafe-assignment": "error",
    "typescript/no-unsafe-call": "error",
    "typescript/no-unsafe-declaration-merging": "error",
    "typescript/no-unsafe-enum-comparison": "error",
    "typescript/no-unsafe-function-type": "error",
    "typescript/no-unsafe-member-access": "error",
    "typescript/no-unsafe-return": "error",
    "typescript/no-unsafe-type-assertion": "error",
    "typescript/no-unsafe-unary-minus": "error",
    "typescript/no-useless-default-assignment": "error",
    "typescript/no-useless-empty-export": "error",
    "typescript/no-var-requires": "error",
    "typescript/no-wrapper-object-types": "error",
    "typescript/non-nullable-type-assertion-style": "off",
    "typescript/only-throw-error": [
      "error",
      {
        allow: [],
        allowRethrowing: false,
        allowThrowingAny: false,
        allowThrowingUnknown: false,
      },
    ],
    "typescript/parameter-properties": [
      "error",
      {
        prefer: "parameter-property",
      },
    ],
    "typescript/prefer-as-const": "error",
    "typescript/prefer-enum-initializers": "error",
    "typescript/prefer-find": "error",
    "typescript/prefer-for-of": "error",
    "typescript/prefer-function-type": "error",
    "typescript/prefer-includes": "error",
    "typescript/prefer-literal-enum-member": "error",
    "typescript/prefer-namespace-keyword": "off",
    "typescript/prefer-nullish-coalescing": "error",
    "typescript/prefer-optional-chain": "error",
    "typescript/prefer-promise-reject-errors": "error",
    "typescript/prefer-readonly": "error",
    "typescript/prefer-readonly-parameter-types": "error",
    "typescript/prefer-reduce-type-parameter": "off",
    "typescript/prefer-regexp-exec": "error",
    "typescript/prefer-return-this-type": "error",
    "typescript/prefer-string-starts-ends-with": "error",
    "typescript/prefer-ts-expect-error": "error",
    "typescript/promise-function-async": "off",
    "typescript/related-getter-setter-pairs": "error",
    "typescript/require-array-sort-compare": "error",
    "typescript/require-await": "error",
    "typescript/restrict-plus-operands": [
      "error",
      {
        allowAny: false,
        allowBoolean: false,
        allowNullish: false,
        allowNumberAndString: false,
        allowRegExp: false,
        skipCompoundAssignments: false,
      },
    ],
    "typescript/restrict-template-expressions": [
      "error",
      {
        allow: [],
        allowAny: false,
        allowArray: false,
        allowBoolean: false,
        allowNever: false,
        allowNullish: false,
        allowNumber: false,
        allowRegExp: false,
      },
    ],
    "typescript/return-await": ["error", "error-handling-correctness-only"],
    "typescript/strict-boolean-expressions": [
      "error",
      {
        allowAny: false,
        allowNullableBoolean: false,
        allowNullableEnum: false,
        allowNullableNumber: false,
        allowNullableObject: false,
        allowNullableString: false,
        allowNumber: false,
        allowString: false,
      },
    ],
    "typescript/strict-void-return": "error",
    "typescript/switch-exhaustiveness-check": [
      "error",
      {
        allowDefaultCaseForExhaustiveSwitch: false,
        considerDefaultExhaustiveForUnions: false,
        requireDefaultForNonUnion: true,
      },
    ],
    "typescript/triple-slash-reference": "error",
    "typescript/unbound-method": "error",
    "typescript/unified-signatures": "error",
    "typescript/use-unknown-in-catch-callback-variable": "error",
    "unicorn/catch-error-name": "error",
    "unicorn/consistent-assert": "error",
    "unicorn/consistent-date-clone": "error",
    "unicorn/consistent-empty-array-spread": "error",
    "unicorn/consistent-existence-index-check": "error",
    "unicorn/consistent-function-scoping": "error",
    "unicorn/consistent-template-literal-escape": "error",
    "unicorn/custom-error-definition": "error",
    "unicorn/empty-brace-spaces": "error",
    "unicorn/error-message": "error",
    "unicorn/escape-case": "error",
    "unicorn/explicit-length-check": "error",
    "unicorn/explicit-timer-delay": "error",
    "unicorn/filename-case": [
      "error",
      {
        cases: {
          camelCase: true,
          pascalCase: true,
          kebabCase: true,
        },
      },
    ],
    "unicorn/import-style": "error",
    "unicorn/max-nested-calls": "error",
    "unicorn/new-for-builtins": "error",
    "unicorn/no-abusive-eslint-disable": "error",
    "unicorn/no-accessor-recursion": "error",
    "unicorn/no-anonymous-default-export": "error",
    "unicorn/no-array-callback-reference": "error",
    "unicorn/no-array-fill-with-reference-type": "error",
    "unicorn/no-array-for-each": "error",
    "unicorn/no-array-method-this-argument": "error",
    "unicorn/no-array-reduce": [
      "error",
      {
        allowSimpleOperations: false,
      },
    ],
    "unicorn/no-array-reverse": [
      "error",
      {
        allowExpressionStatement: false,
      },
    ],
    "unicorn/no-array-sort": [
      "error",
      {
        allowAfterSpread: false,
        allowExpressionStatement: false,
      },
    ],
    "unicorn/no-await-expression-member": "error",
    "unicorn/no-await-in-promise-methods": "error",
    "unicorn/no-confusing-array-with": "error",
    "unicorn/no-console-spaces": "error",
    "unicorn/no-document-cookie": "error",
    "unicorn/no-empty-file": "error",
    "unicorn/no-hex-escape": "error",
    "unicorn/no-immediate-mutation": "error",
    "unicorn/no-instanceof-array": "error",
    "unicorn/no-instanceof-builtins": "error",
    "unicorn/no-invalid-fetch-options": "error",
    "unicorn/no-invalid-remove-event-listener": "error",
    "unicorn/no-length-as-slice-end": "error",
    "unicorn/no-lonely-if": "error",
    "unicorn/no-magic-array-flat-depth": "error",
    "unicorn/no-negated-condition": "error",
    "unicorn/no-negation-in-equality-check": "error",
    "unicorn/no-nested-ternary": "error",
    "unicorn/no-new-array": "error",
    "unicorn/no-new-buffer": "error",
    "unicorn/no-null": "off",
    "unicorn/no-object-as-default-parameter": "error",
    "unicorn/no-process-exit": "error",
    "unicorn/no-single-promise-in-promise-methods": "error",
    "unicorn/no-static-only-class": "error",
    "unicorn/no-thenable": "error",
    "unicorn/no-this-assignment": "error",
    "unicorn/no-typeof-undefined": "error",
    "unicorn/no-unnecessary-array-flat-depth": "error",
    "unicorn/no-unnecessary-array-splice-count": "error",
    "unicorn/no-unnecessary-await": "error",
    "unicorn/no-unnecessary-slice-end": "error",
    "unicorn/no-unreadable-array-destructuring": "error",
    "unicorn/no-unreadable-iife": "error",
    "unicorn/no-useless-collection-argument": "error",
    "unicorn/no-useless-error-capture-stack-trace": "error",
    "unicorn/no-useless-fallback-in-spread": "error",
    "unicorn/no-useless-iterator-to-array": "error",
    "unicorn/no-useless-length-check": "error",
    "unicorn/no-useless-promise-resolve-reject": "error",
    "unicorn/no-useless-spread": "error",
    "unicorn/no-useless-switch-case": "error",
    "unicorn/no-useless-undefined": "error",
    "unicorn/no-zero-fractions": "error",
    "unicorn/number-literal-case": "error",
    "unicorn/numeric-separators-style": "error",
    "unicorn/prefer-add-event-listener": "error",
    "unicorn/prefer-array-find": "error",
    "unicorn/prefer-array-flat": "error",
    "unicorn/prefer-array-flat-map": "error",
    "unicorn/prefer-array-index-of": "error",
    "unicorn/prefer-array-some": "error",
    "unicorn/prefer-at": "error",
    "unicorn/prefer-bigint-literals": "error",
    "unicorn/prefer-blob-reading-methods": "error",
    "unicorn/prefer-class-fields": "error",
    "unicorn/prefer-classlist-toggle": "error",
    "unicorn/prefer-code-point": "error",
    "unicorn/prefer-date-now": "error",
    "unicorn/prefer-default-parameters": "error",
    "unicorn/prefer-dom-node-append": "error",
    "unicorn/prefer-dom-node-dataset": "error",
    "unicorn/prefer-dom-node-remove": "error",
    "unicorn/prefer-dom-node-text-content": "error",
    "unicorn/prefer-event-target": "error",
    "unicorn/prefer-export-from": "error",
    "unicorn/prefer-global-this": "error",
    "unicorn/prefer-import-meta-properties": "error",
    "unicorn/prefer-includes": "error",
    "unicorn/prefer-keyboard-event-key": "error",
    "unicorn/prefer-logical-operator-over-ternary": "error",
    "unicorn/prefer-math-min-max": "error",
    "unicorn/prefer-math-trunc": "error",
    "unicorn/prefer-modern-dom-apis": "error",
    "unicorn/prefer-modern-math-apis": "error",
    "unicorn/prefer-module": "error",
    "unicorn/prefer-native-coercion-functions": "error",
    "unicorn/prefer-negative-index": "error",
    "unicorn/prefer-node-protocol": "error",
    "unicorn/prefer-number-coercion": "error",
    "unicorn/prefer-number-properties": "error",
    "unicorn/prefer-object-from-entries": "error",
    "unicorn/prefer-optional-catch-binding": "error",
    "unicorn/prefer-prototype-methods": "error",
    "unicorn/prefer-query-selector": "error",
    "unicorn/prefer-reflect-apply": "error",
    "unicorn/prefer-regexp-test": "error",
    "unicorn/prefer-response-static-json": "error",
    "unicorn/prefer-set-has": "error",
    "unicorn/prefer-set-size": "error",
    "unicorn/prefer-single-call": "error",
    "unicorn/prefer-spread": "error",
    "unicorn/prefer-string-raw": "error",
    "unicorn/prefer-string-replace-all": "error",
    "unicorn/prefer-string-slice": "error",
    "unicorn/prefer-string-starts-ends-with": "error",
    "unicorn/prefer-string-trim-start-end": "error",
    "unicorn/prefer-structured-clone": "error",
    "unicorn/prefer-ternary": "off",
    "unicorn/prefer-top-level-await": "error",
    "unicorn/prefer-type-error": "error",
    "unicorn/relative-url-style": "error",
    "unicorn/require-array-join-separator": "error",
    "unicorn/require-module-attributes": "error",
    "unicorn/require-module-specifiers": "error",
    "unicorn/require-number-to-fixed-digits-argument": "error",
    "unicorn/require-post-message-target-origin": "error",
    "unicorn/switch-case-braces": "error",
    "unicorn/switch-case-break-position": "error",
    "unicorn/text-encoding-identifier-case": "error",
    "unicorn/throw-new-error": "error",
    "vitest/consistent-each-for": [
      "error",
      {
        describe: "each",
        it: "each",
        test: "each",
      },
    ],
    "vitest/consistent-test-filename": "error",
    "vitest/consistent-test-it": [
      "error",
      {
        fn: "test",
        withinDescribe: "test",
      },
    ],
    "vitest/consistent-vitest-vi": "error",
    "vitest/expect-expect": "error",
    "vitest/hoisted-apis-on-top": "error",
    "vitest/max-expects": [
      "error",
      {
        max: 5,
      },
    ],
    "vitest/max-nested-describe": [
      "error",
      {
        max: 3,
      },
    ],
    "vitest/no-alias-methods": "error",
    "vitest/no-commented-out-tests": "error",
    "vitest/no-conditional-expect": "error",
    "vitest/no-conditional-in-test": "error",
    "vitest/no-conditional-tests": "error",
    "vitest/no-disabled-tests": "error",
    "vitest/no-duplicate-hooks": "error",
    "vitest/no-focused-tests": "error",
    "vitest/no-hooks": "off",
    "vitest/no-identical-title": "error",
    "vitest/no-import-node-test": "error",
    "vitest/no-importing-vitest-globals": "error",
    "vitest/no-interpolation-in-snapshots": "error",
    "vitest/no-large-snapshots": [
      "error",
      {
        allowedSnapshots: {},
        inlineMaxSize: 10,
        maxSize: 25,
      },
    ],
    "vitest/no-mocks-import": "error",
    "vitest/no-restricted-matchers": "error",
    "vitest/no-restricted-vi-methods": [
      "error",
      {
        advanceTimersByTimeAsync: "Bun 1.4 does not implement vi.advanceTimersByTimeAsync().",
        advanceTimersToNextFrame: "Bun 1.4 does not implement vi.advanceTimersToNextFrame().",
        advanceTimersToNextTimerAsync:
          "Bun 1.4 does not implement vi.advanceTimersToNextTimerAsync().",
        defineHelper: "Bun 1.4 does not implement vi.defineHelper().",
        doMock: "Bun 1.4 does not implement vi.doMock().",
        doUnmock: "Bun 1.4 does not implement vi.doUnmock().",
        dynamicImportSettled: "Bun 1.4 does not implement vi.dynamicImportSettled().",
        getMockedSystemTime: "Bun 1.4 does not implement vi.getMockedSystemTime().",
        getRealSystemTime: "Bun 1.4 does not implement vi.getRealSystemTime().",
        hoisted: "Bun 1.4 does not implement vi.hoisted().",
        importActual: "Bun 1.4 does not implement vi.importActual().",
        importMock: "Bun 1.4 does not implement vi.importMock().",
        isMockFunction: "Bun 1.4 does not implement vi.isMockFunction().",
        mocked: "Bun 1.4 does not implement vi.mocked().",
        mockObject: "Bun 1.4 does not implement vi.mockObject().",
        resetConfig: "Bun 1.4 does not implement vi.resetConfig().",
        resetModules: "Bun 1.4 does not implement vi.resetModules().",
        runAllTicks: "Bun 1.4 does not implement vi.runAllTicks().",
        runAllTimersAsync: "Bun 1.4 does not implement vi.runAllTimersAsync().",
        runOnlyPendingTimersAsync: "Bun 1.4 does not implement vi.runOnlyPendingTimersAsync().",
        setConfig: "Bun 1.4 does not implement vi.setConfig().",
        setSystemTime: "Bun 1.4 does not implement vi.setSystemTime().",
        setTimerTickMode: "Bun 1.4 does not implement vi.setTimerTickMode().",
        stubEnv: "Bun 1.4 does not implement vi.stubEnv().",
        stubGlobal: "Bun 1.4 does not implement vi.stubGlobal().",
        unmock: "Bun 1.4 does not implement vi.unmock().",
        unstubAllEnvs: "Bun 1.4 does not implement vi.unstubAllEnvs().",
        unstubAllGlobals: "Bun 1.4 does not implement vi.unstubAllGlobals().",
        waitFor: "Bun 1.4 does not implement vi.waitFor().",
        waitUntil: "Bun 1.4 does not implement vi.waitUntil().",
      },
    ],
    "vitest/no-standalone-expect": "error",
    "vitest/no-test-prefixes": "error",
    "vitest/no-test-return-statement": "error",
    "vitest/no-unneeded-async-expect-function": "error",
    "vitest/padding-around-after-all-blocks": "error",
    "vitest/padding-around-test-blocks": "error",
    "vitest/prefer-called-exactly-once-with": "off",
    "vitest/prefer-called-once": "off",
    "vitest/prefer-called-times": "error",
    "vitest/prefer-called-with": "error",
    "vitest/prefer-comparison-matcher": "error",
    "vitest/prefer-describe-function-title": "error",
    "vitest/prefer-each": "error",
    "vitest/prefer-equality-matcher": "error",
    "vitest/prefer-expect-assertions": "error",
    "vitest/prefer-expect-resolves": "off",
    "vitest/prefer-expect-type-of": "error",
    "vitest/prefer-hooks-in-order": "error",
    "vitest/prefer-hooks-on-top": "error",
    "vitest/prefer-import-in-mock": "off",
    "vitest/prefer-importing-vitest-globals": "off",
    "vitest/prefer-lowercase-title": "error",
    "vitest/prefer-mock-promise-shorthand": "error",
    "vitest/prefer-mock-return-shorthand": "error",
    "vitest/prefer-snapshot-hint": ["error", "always"],
    "vitest/prefer-spy-on": "error",
    "vitest/prefer-strict-boolean-matchers": "error",
    "vitest/prefer-strict-equal": "error",
    "vitest/prefer-to-be": "error",
    "vitest/prefer-to-be-falsy": "off",
    "vitest/prefer-to-be-object": "error",
    "vitest/prefer-to-be-truthy": "off",
    "vitest/prefer-to-contain": "error",
    "vitest/prefer-to-have-been-called-times": "error",
    "vitest/prefer-to-have-length": "error",
    "vitest/prefer-todo": "off",
    "vitest/require-awaited-expect-poll": "off",
    "vitest/require-hook": "error",
    "vitest/require-local-test-context-for-concurrent-snapshots": "off",
    "vitest/require-mock-type-parameters": "error",
    "vitest/require-test-timeout": "error",
    "vitest/require-to-throw-message": "error",
    "vitest/require-top-level-describe": [
      "error",
      {
        maxNumberOfTopLevelDescribes: 1,
      },
    ],
    "vitest/valid-describe-callback": "error",
    "vitest/valid-expect": "error",
    "vitest/valid-expect-in-promise": "error",
    "vitest/valid-title": "error",
    "vitest/warn-todo": "error",
  },
  overrides: [
    {
      files: ["*.config.ts"],
      rules: {
        "import/no-nodejs-modules": "off",
      },
    },
    {
      files: ["**/*.ts", "**/*.tsx", "**/*.cts", "**/*.mts"],
      rules: {
        "eslint/default-case": "off",
      },
    },
    {
      files: ["**/*.d.ts", "**/*.d.cts", "**/*.d.mts"],
      rules: {
        "unicorn/require-module-specifiers": "off",
      },
    },
    {
      files: ["**/*.js", "**/*.jsx", "**/*.cjs", "**/*.mjs"],
      rules: {
        "eslint/no-undef": "error",
        "jsdoc/require-param-type": "error",
      },
    },
    {
      files: [
        "**/*.test.js",
        "**/*.test.jsx",
        "**/*.test.cjs",
        "**/*.test.mjs",
        "**/*.test.ts",
        "**/*.test.tsx",
        "**/*.test.cts",
        "**/*.test.mts",
        "**/*_test.js",
        "**/*_test.jsx",
        "**/*_test.cjs",
        "**/*_test.mjs",
        "**/*_test.ts",
        "**/*_test.tsx",
        "**/*_test.cts",
        "**/*_test.mts",
        "**/*.spec.js",
        "**/*.spec.jsx",
        "**/*.spec.cjs",
        "**/*.spec.mjs",
        "**/*.spec.ts",
        "**/*.spec.tsx",
        "**/*.spec.cts",
        "**/*.spec.mts",
        "**/*_spec.js",
        "**/*_spec.jsx",
        "**/*_spec.cjs",
        "**/*_spec.mjs",
        "**/*_spec.ts",
        "**/*_spec.tsx",
        "**/*_spec.cts",
        "**/*_spec.mts",
      ],
      env: {
        vitest: true,
      },
      rules: {
        "eslint/no-restricted-imports": [
          "error",
          {
            paths: [
              {
                message: "Use Bun test globals so Oxlint can apply the complete Vitest ruleset.",
                name: "bun:test",
              },
            ],
          },
        ],
        "import/unambiguous": "off",
      },
    },
  ],
});
